export interface User {
    country: string,
    city: string,
    address_1: string,
    reason_for_recall: string,
    address_2: string,
    product_quantity: string,
    code_info: string,
    center_classification_date: string,
    distribution_pattern: string,
    state: string,
    product_description: string,
    report_date: string,
    classification: string,
    openfda: Object,
    recalling_firm: string,
    recall_number: string,
    initial_firm_notification: string,
    product_type: string,
    event_id: string,
    more_code_info: string,
    recall_initiation_date: string,
    postal_code: string,
    voluntary_mandated: string,
    status: string
}
